version: '3.8'
services:
    mongodb_contenedor:
        container_name: mongodb
        image: mongo:4.0.25
        restart: always
        volumes:
        - ./data:/data/db
        ports:
        - "4000:27017"
        - "4001:28017"
    flask:
        build: ./
        image: webapp:1
        container_name: flask
        restart: always
        environment:
        - APP_NAME=/app/src/app
         - APP_PORT:5000
         - MONGODB_HOSTNAME:mongodb
         - MONGODB_DATABASE:flaskdb
        depends_on: 
        - mongodb_contenedor
        ports:
        - "5000:5000"
        volumes:
        - ./src:/app/src
