version: '3.8'
services:
  mongodb_contenedor:
    container_name: mongodb
    image: mongo:4.0.25
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  email:
    stdin_open: true
    tty: true
    build: ./
    image: webapp:1
    container_name: email_server
    ports:
      - '8025:8025'
    entrypoint: ["python3", "-m", "smtpd", "--nosetuid", "--class", "DebuggingServer", "email_server:8025"]
  flask:
    stdin_open: true
    tty: true
    image: webapp:1
    container_name: flask
    restart: always
    environment:
      - APP_NAME=./run.py
      - FLASK_ENV=development
    depends_on:
      - email
      - mongodb_contenedor
    ports:
      - '5000:5000'
    volumes:
      - ./app:/app/app
      - ./package.json:/app/package.json
    entrypoint: ["python3","run.py"]

