import unittest
from .base_test import BaseSeleniumUnitTest

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestComentarpublicacion(BaseSeleniumUnitTest):
  def setUp(self):
    super().setUp()
    self.page_url = "http://localhost:5000/mural/publicacion/detalle/"
  
  def test_comentarpublicacion(self):
    # Test name: comentarpublicacion
    # Step # | name | target | value | comment
    # 1 | open | http://localhost:5000/mural/1 |  | 
    self.driver.get("http://localhost:5000/mural/1")
    # 2 | setWindowSize | 1278x727 |  | 
    self.driver.set_window_size(1278, 727)
    # 3 | click | linkText=See publication |  | 
    self.driver.find_element(By.LINK_TEXT, "See publication").click()
    # 4 | click | id=text-comment |  | 
    self.driver.find_element(By.ID, "text-comment").click()
    # 5 | type | id=text-comment | Comentario Automatizado | 
    self.driver.find_element(By.ID, "text-comment").send_keys("Comentario Automatizado")
    # 6 | click | id=comentar |  | 
    self.driver.find_element(By.ID, "comentar").click()
  
if __name__ == '__main__':
    unittest.main()