# Generated by Selenium IDE
import unittest, os
from .base_test import BaseSeleniumUnitTest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait as ui
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

class TestChat(BaseSeleniumUnitTest):
  
  def test_chat(self):

    self.driver.get("http://localhost:5000/")

    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | diego@mail.com
    self.driver.find_element(By.ID, "email").send_keys("diego@mail.com")
    # 5 | type | id=password | Dev123456
    self.driver.find_element(By.ID, "password").send_keys("Dev123456")
    # 6 | click | css=.btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

    # Test name: chat
    # Step # | name | target | value
    # 1 | open | /mural/1 | 
    self.driver.get("http://localhost:5000/mural/1")
    # 3 | click | css=.btn-dark:nth-child(1) | 

    self.driver.find_element(By.ID, "see-profile-of-aaron_morillo").click()

    self.driver.find_element(By.ID, "go-to-chat").click()

    # 4 | click | id=message-input | 
    self.driver.find_element(By.ID, "message-input-text").click()
    # 5 | type | id=message-input | Hello there!
    self.driver.find_element(By.ID, "message-input-text").send_keys("Hello there from here!")
    # 6 | click | css=.bi | 
    self.driver.find_element(By.ID, "send-button").click()
    bodyText = self.driver.find_element(By.TAG_NAME, "body").text
    self.assertTrue("Hello there from here!" in bodyText)

 
if __name__ == '__main__':
    unittest.main()