# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditprofile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editprofile(self):
    # Test name: edit-profile
    # Step # | name | target | value
    # 1 | open | /mural/1 | 
    self.driver.get("http://localhost:5000/mural/1")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | id=ver-mi-perfil-boton | 
    self.driver.find_element(By.ID, "ver-mi-perfil-boton").click()
    # 4 | click | css=#editar-perfil-boton > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, "#editar-perfil-boton > .btn").click()
    # 5 | click | id=nombre_foto | 
    self.driver.find_element(By.ID, "nombre_foto").click()
    # 6 | type | id=nombre_foto | C:\fakepath\tonos.jpg
    self.driver.find_element(By.ID, "nombre_foto").send_keys("C:\\fakepath\\tonos.jpg")
    # 7 | click | id=actualizar-perfil-boton | 
    self.driver.find_element(By.ID, "actualizar-perfil-boton").click()
  
