# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestConfig():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_config(self):
    # Test name: Config
    # Step # | name | target | value
    # 1 | open | http://localhost:5000/configuracion | 
    self.driver.get("http://localhost:5000/configuracion")
    # 2 | setWindowSize | 682x691 | 
    self.driver.set_window_size(682, 691)
    # 3 | click | id=notificaciones-comentarios | 
    self.driver.find_element(By.ID, "notificaciones-comentarios").click()
    # 4 | click | css=.btn-primary:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(1)").click()

    self.assertEqual(self.driver.find_element(By.ID, "notificaciones-comentarios").getAttribute("value"), False)
  
