# Generated by Selenium IDE
import unittest, os
from .base_test import BaseSeleniumUnitTest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditprofile(BaseSeleniumUnitTest):
  
  def test_editprofile(self):

    self.driver.get("http://localhost:5000/")
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | diego@mail.com
    self.driver.find_element(By.ID, "email").send_keys("diego@mail.com")
    # 5 | type | id=password | Dev123456
    self.driver.find_element(By.ID, "password").send_keys("Dev123456")
    # 6 | click | css=.btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()

    # Test name: edit-profile
    # Step # | name | target | value
    # 1 | open | /mural/1 | 
    self.driver.get("http://localhost:5000/mural/1")
    # 3 | click | linkText=Ver mi perfil | 
    self.driver.find_element(By.ID, "go-chat-button-with-aaron_morillo").click()
    self.assertEqual(self.driver.current_url, "http://localhost:5000/ver-perfil/aaron_morillo")

    self.driver.quit()
  
if __name__ == '__main__':
    unittest.main()