# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditprofile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editprofile(self):
    # Test name: edit-profile
    # Step # | name | target | value
    # 1 | open | /mural/1 | 
    self.driver.get("http://localhost:5000/mural/1")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | linkText=Ver mi perfil | 
    self.driver.find_element(By.LINK_TEXT, "Ver mi perfil").click()
    # 4 | click | css=a:nth-child(1) > .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .btn-primary").click()
    # 5 | click | id=color | 
    self.driver.find_element(By.ID, "color").click()
    # 6 | type | id=color | Azul 
    self.driver.find_element(By.ID, "color").send_keys("Azul ")
    # 7 | click | id=libro | 
    self.driver.find_element(By.ID, "libro").click()
    # 8 | type | id=libro | TLOR
    self.driver.find_element(By.ID, "libro").send_keys("TLOR")
    # 9 | click | id=musica | 
    self.driver.find_element(By.ID, "musica").click()
    # 10 | type | id=musica | Pop
    self.driver.find_element(By.ID, "musica").send_keys("Pop")
    # 11 | click | id=lenguajes_programacion | 
    self.driver.find_element(By.ID, "lenguajes_programacion").click()
    # 12 | type | id=lenguajes_programacion | PhP, Ruby
    self.driver.find_element(By.ID, "lenguajes_programacion").send_keys("PhP, Ruby")
    # 13 | click | id=video_juegos | 
    self.driver.find_element(By.ID, "video_juegos").click()
    # 14 | type | id=video_juegos | TLOU II, Sekiro
    self.driver.find_element(By.ID, "video_juegos").send_keys("TLOU II, Sekiro")
    # 15 | click | id=descripcion | 
    self.driver.find_element(By.ID, "descripcion").click()
    # 16 | type | id=descripcion | Soy un estudiante
    self.driver.find_element(By.ID, "descripcion").send_keys("Soy un estudiante")
    # 17 | click | id=nombre_foto | 
    self.driver.find_element(By.ID, "nombre_foto").click()
    # 18 | click | css=.col > .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".col > .btn-primary").click()
    # 19 | click | linkText=Ver mi perfil | 
    self.driver.find_element(By.LINK_TEXT, "Ver mi perfil").click()
    # 20 | close |  | 
    self.driver.close()
    # 21 | click | id=ver-mi-perfil-boton | 
    self.driver.find_element(By.ID, "ver-mi-perfil-boton").click()
  
